apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n47fxz3ah-python 
  janus-idp.io/tekton: n47fxz3ah-python
  backstage.io/kubernetes-id: n47fxz3ah-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n47fxz3ah-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml