apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n47fxz3ah-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n47fxz3ah-python 
  name: n47fxz3ah-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n47fxz3ah-python 
